---
name: Bug Report
about: Create a report to help us improve SDEverse
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## Bug Description
Clear description of what the bug is.

## Steps to Reproduce
1. Go to '...'
2. Click on '...'
3. See error

## Expected vs Actual Behavior
- Expected: What should happen
- Actual: What actually happened

## Environment
- OS: [e.g. Windows 10, macOS, Ubuntu]
- Browser: [e.g. Chrome, Firefox, Safari]  
- Version: [e.g. 1.0.0]

## Additional Context
Screenshots, error logs, or other relevant information.