---
name: Question
about: Ask a question about SDEverse
title: '[QUESTION] '
labels: ['question']
assignees: ''
---

## Question
What would you like to know?

## Context
What are you trying to accomplish? What have you already tried?

## Area
Which part of SDEverse does this relate to?
- [ ] Frontend (React, UI/UX)
- [ ] Backend (Node.js, API) 
- [ ] Setup/Development
- [ ] General usage
- [ ] Other

## Additional Details
Code snippets, error messages, or other relevant information.